### PR TITLE
Updated dependencies to work on flutter 2.2.0

### PR DESCRIPTION
**Pull request by aumb**
Hey! 

I noticed the app was not working on the newest version of flutter. Here are the changes I made:

- I updated most of the dependencies to the latest version, and did the necessary changes for depreciated usages.

- I changed the mock package from `Mockito` to `Mocktail` (https://pub.dev/packages/mocktail)

- I upgrade the gradle version

- I set the IOS platform to `9` for sqflite to work

Please let me know if there's something you need me to change 💙

### CODE REVIEW

**Comment by vedartm** [comment]
Hi @aumb. Really appreciate you making this PR. Can you please fix build workflow. I am assuming the issue is the flutter version used in [build.yaml](https://github.com/excogitatr/rick-and-morty-info/blob/develop/.github/workflows/build.yaml)

**Comment by aumb** [comment]
> Hi @aumb. Really appreciate you making this PR. Can you please fix build workflow. I am assuming the issue is the flutter version used in [build.yaml](https://github.com/excogitatr/rick-and-morty-info/blob/develop/.github/workflows/build.yaml)

Yes sure on it!

I can migrate the application to null safety if you'd like as well.

**Comment by vedartm** [comment]
Migrating to null safety would be great @aumb

**Comment by aumb** [comment]
> Migrating to null safety would be great @aumb

Okay will migrate as soon as this is merged so i can worked based on this. I'll open another pull request for null safety if this is all ok with you.

**Comment by vedartm** [comment]
Thanks for contributing @aumb 🎉

**Pull request merged**
